"""Note table updated

Revision ID: 67234ae0ba3a
Revises: 84e5f43a607f
Create Date: 2023-11-16 08:49:17.747493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67234ae0ba3a'
down_revision = '84e5f43a607f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###
